INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('userA', 'qwer', true);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('userB', 'qwerqwer', true);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('sample', 'sample', true);

INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (1, 'Sample', 'userA', TIMESTAMP '2015-08-05 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (2, 'Springframework', 'userB', TIMESTAMP '2015-08-06 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (3, 'Springframework Security', 'sample', TIMESTAMP '2015-08-07 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (4, 'HSQLDB', 'userA', TIMESTAMP '2015-08-08 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (5, 'Freemarker', 'userB', TIMESTAMP '2015-08-09 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (6, 'CKEditor', 'sample', TIMESTAMP '2015-08-10 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (7, 'Servlet 3.0', 'userA', TIMESTAMP '2015-08-11 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (8, 'Jackson', 'sample', TIMESTAMP '2015-08-12 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (9, 'MyBatis', 'userA', TIMESTAMP '2015-08-13 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (10, 'Tomcat', 'userB', TIMESTAMP '2015-08-14 16:45:15', CURRENT_TIMESTAMP);
INSERT INTO ARTICLES (ARTICLE_KEY, TITLE, USERNAME, CREATE_DATE, MODIFY_DATE)
VALUES (11, 'Application', 'sample', TIMESTAMP '2015-08-15 16:45:15', CURRENT_TIMESTAMP);